import {
  americanoPortrait1,
  americanoPortrait2,
  americanoPortrait3,
  americanoSquare1,
  americanoSquare2,
  americanoSquare3,
  arabicaCoffeeBeansPortrait,
  arabicaCoffeeBeansSquare,
  bagOrange,
  bagWhite,
  bellOrange,
  bellWhite,
  blackCoffeePortrait1,
  blackCoffeePortrait2,
  blackCoffeePortrait3,
  blackCoffeeSquare1,
  blackCoffeeSquare2,
  blackCoffeeSquare3,
  cappuccinoPortrait1,
  cappuccinoPortrait2,
  cappuccinoPortrait3,
  cappuccinoSquare1,
  cappuccinoSquare2,
  cappuccinoSquare3,
  espressoPortrait1,
  espressoPortrait2,
  espressoPortrait3,
  espressoSquare1,
  espressoSquare2,
  espressoSquare3,
  excelsaCoffeeBeansPortrait,
  excelsaCoffeeBeansSquare,
  heartOrange,
  heartWhite,
  homeOrange,
  homeWhite,
  lattePortrait1,
  lattePortrait2,
  lattePortrait3,
  latteSquare1,
  latteSquare2,
  latteSquare3,
  libericaCoffeeBeansPortrait,
  libericaCoffeeBeansSquare,
  macchiatoPortrait1,
  macchiatoPortrait2,
  macchiatoPortrait3,
  macchiatoSquare1,
  macchiatoSquare2,
  macchiatoSquare3,
  robustaCoffeeBeansPortrait,
  robustaCoffeeBeansSquare,
} from '../assets';

export const CoffeeData = [
  {
    id: 12733,
    name: 'Americano',
    description: `The Americano is another popular type of coffee drink, and it's very easy to make! It's just espresso with hot water dripping over it. The name came about during World War II when European baristas added water to their espresso drinks for the American soldiers stationed there. The resulting drink had a smoother, less concentrated flavour than espresso and thus the Americano was born.`,
    roasted: 'Medium Roasted',
    imagelink_square: americanoSquare1,
    imagelink_portrait: americanoPortrait1,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 80.15,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 0,
    amount: 1,
  },
  {
    id: 325662,
    name: 'Americano',
    description: `The Americano is another popular type of coffee drink, and it's very easy to make! It's just espresso with hot water dripping over it. The name came about during World War II when European baristas added water to their espresso drinks for the American soldiers stationed there. The resulting drink had a smoother, less concentrated flavour than espresso and thus the Americano was born.`,
    roasted: 'Medium Roasted',
    imagelink_square: americanoSquare2,
    imagelink_portrait: americanoPortrait2,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 20.9,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 1,
    amount: 1,
  },
  {
    id: 562727,
    name: 'Americano',
    description: `The Americano is another popular type of coffee drink, and it's very easy to make! It's just espresso with hot water dripping over it. The name came about during World War II when European baristas added water to their espresso drinks for the American soldiers stationed there. The resulting drink had a smoother, less concentrated flavour than espresso and thus the Americano was born.`,
    roasted: 'Medium Roasted',
    imagelink_square: americanoSquare3,
    imagelink_portrait: americanoPortrait3,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 50.9,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 2,
    amount: 1,
  },
  {
    id: 5672,
    name: 'Black Coffee',
    description: `Black coffee is arguably the most common type of coffee drink out there. Its popularity can be mainly attributed to how easy it is to make this beverage, be it drip, pour-over, French press, or anything else. Black coffee is usually served with no add-ins.`,
    roasted: 'Medium Roasted',
    imagelink_square: blackCoffeeSquare1,
    imagelink_portrait: blackCoffeePortrait1,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 25.9,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 3,
    amount: 1,
  },
  {
    id: 567827,
    name: 'Black Coffee',
    description: `Black coffee is arguably the most common type of coffee drink out there. Its popularity can be mainly attributed to how easy it is to make this beverage, be it drip, pour-over, French press, or anything else. Black coffee is usually served with no add-ins.`,
    roasted: 'Medium Roasted',
    imagelink_square: blackCoffeeSquare2,
    imagelink_portrait: blackCoffeePortrait2,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 90.9,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 4,
    amount: 1,
  },
  {
    id: 562556,
    name: 'Black Coffee',
    description: `Black coffee is arguably the most common type of coffee drink out there. Its popularity can be mainly attributed to how easy it is to make this beverage, be it drip, pour-over, French press, or anything else. Black coffee is usually served with no add-ins.`,
    roasted: 'Medium Roasted',
    imagelink_square: blackCoffeeSquare3,
    imagelink_portrait: blackCoffeePortrait3,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 40.9,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 5,
    amount: 1,
  },
  {
    id: 72828,
    name: 'Cappuccino',
    description: `Cappuccinos are a classic Italian type of coffee drink made of espresso, steamed milk, and thick foam in equal parts. The name comes from the resemblance to the hoods worn by Capuchin monks. Making cappuccino is relatively easy and can be done at home too if you know how to make espresso.`,
    roasted: 'Medium Roasted',
    imagelink_square: cappuccinoSquare1,
    imagelink_portrait: cappuccinoPortrait1,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 36.9,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 6,
    amount: 1,
  },
  {
    id: 9928,
    name: 'Cappuccino',
    description: `Cappuccinos are a classic Italian type of coffee drink made of espresso, steamed milk, and thick foam in equal parts. The name comes from the resemblance to the hoods worn by Capuchin monks. Making cappuccino is relatively easy and can be done at home too if you know how to make espresso.`,
    roasted: 'Medium Roasted',
    imagelink_square: cappuccinoSquare2,
    imagelink_portrait: cappuccinoPortrait2,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 88.9,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 7,
    amount: 1,
  },
  {
    id: 992772,
    name: 'Cappuccino',
    description: `Cappuccinos are a classic Italian type of coffee drink made of espresso, steamed milk, and thick foam in equal parts. The name comes from the resemblance to the hoods worn by Capuchin monks. Making cappuccino is relatively easy and can be done at home too if you know how to make espresso.`,
    roasted: 'Medium Roasted',
    imagelink_square: cappuccinoSquare3,
    imagelink_portrait: cappuccinoPortrait3,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 80.9,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 8,
    amount: 1,
  },
  {
    id: 7244252,
    name: 'Espresso',
    description: `Espresso is made by forcing nearly boiling water through finely-ground coffee beans, which results in a concentrated, syrup-like coffee drink. This is the base for many Italian beverages in coffee shops. When compared to regular brewed coffee, espresso is much stronger than the other types of coffee drinks. Espressos are enjoyed in shots where a single shot is one ounce and a long (single and double) shot is two ounces in amount, respectively.`,
    roasted: 'Medium Roasted',
    imagelink_square: espressoSquare1,
    imagelink_portrait: espressoPortrait1,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 45.9,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 9,
    amount: 1,
  },
  {
    id: 2672682,
    name: 'Espresso',
    description: `Espresso is made by forcing nearly boiling water through finely-ground coffee beans, which results in a concentrated, syrup-like coffee drink. This is the base for many Italian beverages in coffee shops. When compared to regular brewed coffee, espresso is much stronger than the other types of coffee drinks. Espressos are enjoyed in shots where a single shot is one ounce and a long (single and double) shot is two ounces in amount, respectively.`,
    roasted: 'Medium Roasted',
    imagelink_square: espressoSquare2,
    imagelink_portrait: espressoPortrait2,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 12.9,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 10,
    amount: 1,
  },
  {
    id: 2225261,
    name: 'Espresso',
    description: `Espresso is made by forcing nearly boiling water through finely-ground coffee beans, which results in a concentrated, syrup-like coffee drink. This is the base for many Italian beverages in coffee shops. When compared to regular brewed coffee, espresso is much stronger than the other types of coffee drinks. Espressos are enjoyed in shots where a single shot is one ounce and a long (single and double) shot is two ounces in amount, respectively.`,
    roasted: 'Medium Roasted',
    imagelink_square: espressoSquare3,
    imagelink_portrait: espressoPortrait3,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 90.4,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 11,
    amount: 1,
  },
  {
    id: 826762,
    name: 'Latte',
    description: `A latte is an espresso with steamed milk and a dollop of milk foam on top. This beverage is more prevalent in America than other coffee drinks like cappuccinos because it contains less foam, making it smoother and gentler for those with sensitive palettes. And if you want to spice up your latte, add some flavouring syrup. To make an iced version of this drink, simply pour espresso and steamed milk over ice cubes.`,
    roasted: 'Medium Roasted',
    imagelink_square: latteSquare1,
    imagelink_portrait: lattePortrait1,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 39.9,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 12,
    amount: 1,
  },
  {
    id: 265271,
    name: 'Latte',
    description: `A latte is an espresso with steamed milk and a dollop of milk foam on top. This beverage is more prevalent in America than other coffee drinks like cappuccinos because it contains less foam, making it smoother and gentler for those with sensitive palettes. And if you want to spice up your latte, add some flavouring syrup. To make an iced version of this drink, simply pour espresso and steamed milk over ice cubes.`,
    roasted: 'Medium Roasted',
    imagelink_square: latteSquare2,
    imagelink_portrait: lattePortrait2,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 75.5,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 13,
    amount: 1,
  },
  {
    id: 29082,
    name: 'Latte',
    description: `A latte is an espresso with steamed milk and a dollop of milk foam on top. This beverage is more prevalent in America than other coffee drinks like cappuccinos because it contains less foam, making it smoother and gentler for those with sensitive palettes. And if you want to spice up your latte, add some flavouring syrup. To make an iced version of this drink, simply pour espresso and steamed milk over ice cubes.`,
    roasted: 'Medium Roasted',
    imagelink_square: latteSquare3,
    imagelink_portrait: lattePortrait3,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 69.5,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 14,
    amount: 1,
  },
  {
    id: 67654323223,
    name: 'Macchiato',
    description: `The word "macchiato" means spotted, so a macchiato espresso is an espresso with a splash of milk. Most coffee shops will top off this type of coffee drink with some foamed milk instead of just steamed milk for what's known as a traditional macchiato. `,
    roasted: 'Medium Roasted',
    imagelink_square: macchiatoSquare1,
    imagelink_portrait: macchiatoPortrait1,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 30.5,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 15,
    amount: 1,
  },
  {
    id: 2573322,
    name: 'Macchiato',
    description: `The word "macchiato" means spotted, so a macchiato espresso is an espresso with a splash of milk. Most coffee shops will top off this type of coffee drink with some foamed milk instead of just steamed milk for what's known as a traditional macchiato. `,
    roasted: 'Medium Roasted',
    imagelink_square: macchiatoSquare2,
    imagelink_portrait: macchiatoPortrait2,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 90.5,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 16,
    amount: 1,
  },
  {
    id: 2286e382,
    name: 'Macchiato',
    description: `The word "macchiato" means spotted, so a macchiato espresso is an espresso with a splash of milk. Most coffee shops will top off this type of coffee drink with some foamed milk instead of just steamed milk for what's known as a traditional macchiato. `,
    roasted: 'Medium Roasted',
    imagelink_square: macchiatoSquare3,
    imagelink_portrait: macchiatoPortrait3,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 66.7,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 17,
    amount: 1,
  },
];

export const BeansData = [
  {
    id: 75335735,
    name: 'Robusta Beans',
    description: `Robusta beans are larger and more rounded than the other bean varieties. These plants typically grow much larger than Arabica plants, measuring between 15 and 20 feet. Robusta beans are typically considered to be hardier because they can grow at lower altitudes and resist diseases. But recent research suggests that they don’t handle heat as well as was previously thought.`,
    roasted: 'Medium Roasted',
    imagelink_square: robustaCoffeeBeansSquare,
    imagelink_portrait: robustaCoffeeBeansPortrait,
    ingredients: 'Africa',
    special_ingredient: 'From Africa',
    prices: 19.9,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Bean',
    index: 0,
    amount: 1,
  },
  {
    id: 95050545,
    name: 'Arabica Beans',
    description: `Arabica beans are by far the most popular type of coffee beans, making up about 60% of the world’s coffee. These tasty beans originated many centuries ago in the highlands of Ethiopia, and may even be the first coffee beans ever consumed! The name Arabica likely comes from the beans’ popularity in 7th-century Arabia (present-day Yemen).`,
    roasted: 'Medium Roasted',
    imagelink_square: arabicaCoffeeBeansSquare,
    imagelink_portrait: arabicaCoffeeBeansPortrait,
    ingredients: 'Africa',
    special_ingredient: 'From Africa',
    prices: 55.9,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Bean',
    index: 1,
    amount: 1,
  },
  {
    id: 45080044,
    name: 'Liberica Beans',
    description: `Native to central and western Africa – specifically Liberia, hence its name – Coffea liberica is prized for its piquant floral aroma and bold, smoky flavor profile. Growing from a much larger plant than Arabica or Robusta, most Liberica cherries tend to be irregular in shape and closer to Robusta in size and general appearance. It’s also tolerant of hot, humid climates and does well at low altitude. `,
    roasted: 'Medium Roasted',
    imagelink_square: libericaCoffeeBeansSquare,
    imagelink_portrait: libericaCoffeeBeansPortrait,
    ingredients: 'Malaysia',
    special_ingredient: 'From Malaysia',
    prices: 70.8,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Bean',
    index: 2,
    amount: 1,
  },
  {
    id: 663563856856,
    name: 'Excelsa Beans',
    description: `Excelsa beans grow almost entirely in Southeast Asia, and they’re shaped somewhat like Liberica beans — elongated ovals. These beans grow on large 20 to 30-foot coffee plants at medium altitudes. In terms of flavor, Excelsa beans are pretty unique. They combine light roast traits like tart notes and fruity flavors with flavors that are more reminiscent of dark roasts.`,
    roasted: 'Medium Roasted',
    imagelink_square: excelsaCoffeeBeansSquare,
    imagelink_portrait: excelsaCoffeeBeansPortrait,
    ingredients: 'Malaysia',
    special_ingredient: 'From Malaysia',
    prices: 88.9,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Bean',
    index: 3,
    amount: 1,
  },
];

export const category = [
  {
    id: 1,
    name: 'Americano',
    dataName: 'AmericanoData',
    img: americanoSquare1,
  },
  {
    id: 2,
    name: 'Black Coffee',
    dataName: 'BlackCoffeeData',
    img: blackCoffeeSquare2,
  },
  {
    id: 3,
    name: 'Cappuccino',
    dataName: 'CappuccinoData',
    img: cappuccinoSquare2,
  },
  {
    id: 4,
    name: 'Espresso',
    dataName: 'EspressoData',
    img: espressoSquare3,
  },
  {
    id: 5,
    name: 'Latte',
    dataName: 'LatteData',
    img: latteSquare2,
  },
  {
    id: 6,
    name: 'Macchiato',
    dataName: 'MacchiatoData',
    img: macchiatoSquare2,
  },
];

export const footerLinks = [
  {
    id: 1,
    name: '/',
    imgUrl_white: homeWhite,
    imgUrl_orange: homeOrange,
  },
  {
    id: 2,
    name: '/cart',
    imgUrl_white: bagWhite,
    imgUrl_orange: bagOrange,
  },
  {
    id: 3,
    name: '/favorite',
    imgUrl_white: heartWhite,
    imgUrl_orange: heartOrange,
  },
  {
    id: 4,
    name: '/history',
    imgUrl_white: bellWhite,
    imgUrl_orange: bellOrange,
  },
];

export const testingData = [
  {
    id: 9928,
    name: 'Cappuccino',
    description: `Cappuccinos are a classic Italian type of coffee drink made of espresso, steamed milk, and thick foam in equal parts. The name comes from the resemblance to the hoods worn by Capuchin monks. Making cappuccino is relatively easy and can be done at home too if you know how to make espresso.`,
    roasted: 'Medium Roasted',
    imagelink_square: cappuccinoSquare2,
    imagelink_portrait: cappuccinoPortrait2,
    ingredients: 'Milk',
    special_ingredient: 'With Steamed Milk',
    prices: 4.99,
    average_rating: 4.7,
    ratings_count: '6,879',
    favourite: false,
    type: 'Coffee',
    index: 7,
    amount: 2,
  },
];
